---
- hosts: all
  connection: local
  gather_facts: no
  vars: 
    job_id: "software_install-1d60694a-7965-46e0-8f9b-0887800b3f6d"

  tasks:
    - name: Get vManage Cookie
      uri:
        url: "https://{{ ansible_host }}/j_security_check"
        method: POST
        body:
          j_username: "{{ ansible_user }}"
          j_password: "{{ ansible_password }}"
        body_format: form-urlencoded
        validate_certs: no
      register: login_result
      tags:
        - authenticate
    # - debug: var=login_result.set_cookie

    - name: Get XSRF Token
      uri:
        url: "https://{{ ansible_host }}/dataservice/client/token"
        method: GET
        headers:
          Cookie: "{{ login_result.set_cookie }}"
        validate_certs: no
        return_content: yes
      register: token_result
      tags:
        - authenticate
    # - debug: var=token_result.content

    - name: Get job status and repeat until complete - FAILED == In Progress
      uri:
        method: GET
        url: "https://{{ ansible_host }}/dataservice/device/action/status/{{ job_id }}"
        headers:
          Cookie: "{{ login_result.set_cookie }}"
        validate_certs: no
        return_content: yes
      register: job_status
      # until: job_status.json.data[0].status == "Success" or job_status.json.data[0].status == "Failure" or job_status.json.data[0].status == "Skipped"
      until: job_status.json.summary.status == 'done'
      retries: 60
      delay: 60
      failed_when: job_status.json.data[0].status == "Failed"

    - debug:
        msg:
          currentActivity: "{{ job_status.json.data[0].currentActivity }}"
          status: "{{ job_status.json.data[0].status }}"
          activity: "{{ job_status.json.data[0].activity }}" 